"""Claude Code install helpers."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


INSTALL_MARKER = "<!-- Generated by multi-agent-brief claude install. -->"


def register(subparsers: argparse._SubParsersAction) -> None:
    claude_parser = subparsers.add_parser(
        "claude",
        help="Install or inspect Claude Code assets for MABW.",
    )
    actions = claude_parser.add_subparsers(dest="claude_action", required=True)

    install = actions.add_parser(
        "install",
        help="Install /generate-brief and MABW subagents into ~/.claude.",
    )
    install.add_argument(
        "--repo-workdir",
        default=".",
        help="MABW source repository root (default: current directory).",
    )
    install.add_argument(
        "--target",
        default=str(Path.home() / ".claude"),
        help="Claude Code user config directory (default: ~/.claude).",
    )
    install.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing non-MABW files in target locations.",
    )
    install.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned writes without changing files.",
    )


def handle(args: argparse.Namespace) -> int:
    if args.claude_action == "install":
        try:
            return _install(args)
        except RuntimeError as exc:
            print(f"[claude install] {exc}")
            return 1
    return 1


def _install(args: argparse.Namespace) -> int:
    repo = Path(args.repo_workdir).expanduser().resolve()
    target = Path(args.target).expanduser().resolve()
    command_src = repo / ".claude" / "commands" / "generate-brief.md"
    agents_src = repo / ".claude" / "agents"
    if not command_src.exists():
        raise RuntimeError(f"Claude command not found: {command_src}")
    if not agents_src.exists():
        raise RuntimeError(f"Claude agents directory not found: {agents_src}")

    command_dst = target / "commands" / "generate-brief.md"
    agents_dst = target / "agents" / "mabw"
    command_text = _installed_command_text(command_src, repo=repo)

    writes: list[tuple[Path, str | Path]] = [(command_dst, command_text)]
    for src in sorted(agents_src.glob("*.md")):
        writes.append((agents_dst / src.name, src))

    for dst, content in writes:
        if dst.exists() and not args.force:
            if isinstance(content, str):
                existing = dst.read_text(encoding="utf-8")
                if existing == content or INSTALL_MARKER in existing:
                    continue
            elif dst.read_bytes() == content.read_bytes():
                continue
            raise RuntimeError(
                f"Refusing to overwrite existing file without --force: {dst}"
            )

    if args.dry_run:
        for dst, _content in writes:
            print(f"[claude install] would write {dst}")
        return 0

    for dst, content in writes:
        dst.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(content, str):
            dst.write_text(content, encoding="utf-8")
        else:
            shutil.copy2(content, dst)
        print(f"[claude install] wrote {dst}")

    print("")
    print("[claude install] Installed /generate-brief for Claude Code CLI and Claude Desktop Code tab.")
    print("[claude install] In Claude Code, type '/' and confirm /generate-brief is listed.")
    return 0


def _installed_command_text(command_src: Path, *, repo: Path) -> str:
    text = command_src.read_text(encoding="utf-8")
    repo_text = repo.as_posix()
    text = text.replace(
        "Read shared contract references before delegation:\n\n"
        "- `configs/orchestrator_contract.yaml`\n"
        "- `configs/stage_specs.yaml`\n"
        "- `configs/artifact_contracts.yaml`\n"
        "- `configs/policy_packs/default.yaml`",
        "This command was installed from the MABW source repository:\n\n"
        f"- `{repo_text}`\n\n"
        "Read shared contract references before delegation:\n\n"
        f"- `{repo_text}/configs/orchestrator_contract.yaml`\n"
        f"- `{repo_text}/configs/stage_specs.yaml`\n"
        f"- `{repo_text}/configs/artifact_contracts.yaml`\n"
        f"- `{repo_text}/configs/policy_packs/default.yaml`",
    )
    text = text.replace(
        "You are the Orchestrator main agent generating a real user-facing brief for workspace: $ARGUMENTS.",
        "You are the Orchestrator main agent generating a real user-facing brief for workspace: $ARGUMENTS.\n\n"
        "If $ARGUMENTS is a relative path, resolve it from the current Claude Code project folder. "
        "If the workspace is not found, ask for an absolute workspace path before proceeding.",
    )
    return f"{INSTALL_MARKER}\n{text}"
