import assert from 'node:assert/strict';
import {createSourceLibrarySearch} from '../frontend/source-library-search.js';
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));
const pending=[];
const search=createSourceLibrarySearch({delay:0,onChange:()=>{},api:path=>new Promise((resolve,reject)=>pending.push({path,resolve,reject}))});
const input=(query,extra={})=>({query,type:'',channel:'',status:'',workspace:'w1',sources:[],...extra});
const page=(id,extra={})=>({items:id?[{source_id:id}]:[],unsearched:[],unsearched_count:0,scanned_candidates:1,total_candidates:2,next_cursor:null,exhausted:true,...extra});
search.update(input('A'));await tick();search.update(input('B'));await tick();search.update(input('A'));await tick();
pending[0].resolve(page('old-A'));pending[1].reject(new Error('old failure'));await tick();
assert.equal(search.state.items.length,0);assert.equal(search.state.error,'');
pending[2].resolve(page('current-A',{next_cursor:'next',exhausted:false,unsearched:[{source_id:'large',reason:'too_large'}],unsearched_count:1}));await tick();
assert.equal(search.state.items[0].source_id,'current-A');assert.equal(pending.length,3,'does not automatically request another page');
search.more();await tick();assert.match(pending[3].path,/cursor=next/);
pending[3].resolve(page('next-A'));await tick();
assert.equal(search.state.exhausted,true);assert.equal(search.state.unsearchedCount,1,'last page preserves unread files from earlier pages');
assert.equal(search.state.scanned,2);
search.update(input('A',{status:'failed'}));await tick();search.update(input(''));pending[4].resolve(page('wrong-filter'));await tick();
assert.equal(search.state.items.length,0);assert.equal(search.state.query,'');
search.update(input('A'));await tick();search.update(input('A',{workspace:'w2'}));await tick();pending[5].resolve(page('wrong-workspace'));await tick();
assert.equal(search.state.items.length,0);
pending[6].resolve(page('right-workspace'));await tick();
assert.equal(search.state.items[0].source_id,'right-workspace');
search.update(input('A',{workspace:'w2'}));await tick();assert.equal(pending.length,7,'identical state polling does not start another query');
console.log('PASS: bounded source search discards stale successes/errors and accumulates unread state only on explicit continuation');
