import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('frontend/app.js','utf8');
const code=source.slice(source.indexOf('function restoreDraft(){'),source.indexOf('function renderChatRuntimePermissions()'));
const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id)};
const c=vm.createContext({$:el,chat:{id:'existing',drafts:new Map(),session:{runtime:{backend:'claude',model:'default'}}},state:{settings:{agent_backend:'claude',model:'default',model_selection_required:true}},effortValue:()=>null,assignEffort:()=>{},renderAttachments:()=>{},updateComposer:()=>{},autoSizeChatInput:()=>{}});
vm.runInContext(code,c);vm.runInContext('restoreDraft()',c);assert.equal(el('chat-model').value,'default');
c.chat.id=null;c.chat.session=null;c.chat.drafts.set('new',{text:'unsent message',backend:'claude',model:'default'});
vm.runInContext('restoreDraft()',c);assert.equal(el('chat-model').value,'default');assert.equal(el('chat-input').value,'unsent message');
c.chat.drafts.set('new',{text:'keep this text',backend:'codex',model:'old-codex-model'});
vm.runInContext('restoreDraft()',c);assert.equal(el('chat-model').value,'');assert.equal(el('chat-input').value,'keep this text');
console.log('PASS: explicit chat choice survives pending workspace selection; model does not cross runtime boundaries');
