// Git's Windows checkout must not rewrite byte-verified build artifacts.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

const tmp=fs.realpathSync(os.tmpdir());
const root=fs.mkdtempSync(path.join(tmp,'briefloop-checkout-eol-'));
const git=(...args)=>execFileSync('git',args,{cwd:root,stdio:'pipe'});
const artifacts=['src/briefloop/static/app.js','src/briefloop/static/frontend-licenses.txt'];
const bytes=Buffer.from('generated line one\ngenerated line two\n');
try{
 git('init');git('config','core.autocrlf','true');
 fs.mkdirSync(path.join(root,'src/briefloop/static'),{recursive:true});
 for(const name of artifacts)fs.writeFileSync(path.join(root,name),bytes);
 fs.writeFileSync(path.join(root,'control.txt'),bytes);
 git('add','.');
 for(const name of [...artifacts,'control.txt'])fs.unlinkSync(path.join(root,name));
 git('checkout-index','--all','--force');
 // Establish that this checkout reproduces the CI failure without attributes.
 for(const name of artifacts)assert.notDeepEqual(fs.readFileSync(path.join(root,name)),bytes);
 fs.copyFileSync(new URL('../.gitattributes',import.meta.url),path.join(root,'.gitattributes'));
 git('add','.gitattributes');
 for(const name of artifacts)fs.unlinkSync(path.join(root,name));
 git('checkout-index','--all','--force');
 for(const name of artifacts)assert.deepEqual(fs.readFileSync(path.join(root,name)),bytes);
 // The fix is scoped to generated bytes, not a global checkout preference.
 assert.match(fs.readFileSync(path.join(root,'control.txt'),'utf8'),/\r\n/);
 console.log('PASS: Windows-style Git checkout preserves generated bundle and license bytes');
}finally{
 assert.equal(path.dirname(fs.realpathSync(root)),tmp);
 fs.rmSync(root,{recursive:true,force:true});
}
