"""Tests for shared installer write safety."""

from __future__ import annotations

import pytest

from multi_agent_brief.install.writer import (
    InstallWriteError,
    PlannedWrite,
    apply_planned_writes,
)


def test_apply_planned_writes_writes_files_under_root(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    dst = root / "commands" / "generate-brief.md"

    written = apply_planned_writes(
        writes=[PlannedWrite(dst, "content\n")],
        root=root,
        generated_markers=("Generated by test",),
    )

    assert written == [dst]
    assert dst.read_text(encoding="utf-8") == "content\n"


def test_apply_planned_writes_dry_run_does_not_write(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    dst = root / "commands" / "generate-brief.md"

    planned = apply_planned_writes(
        writes=[PlannedWrite(dst, "content\n")],
        root=root,
        dry_run=True,
    )

    assert planned == [dst]
    assert not dst.exists()


def test_apply_planned_writes_refuses_non_generated_existing_file(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    dst = root / "AGENTS.md"
    dst.write_text("user notes\n", encoding="utf-8")

    with pytest.raises(InstallWriteError, match="non-MABW file"):
        apply_planned_writes(
            writes=[PlannedWrite(dst, "new content\n")],
            root=root,
            generated_markers=("Generated by test",),
        )

    assert dst.read_text(encoding="utf-8") == "user notes\n"


def test_apply_planned_writes_refreshes_generated_existing_file(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    dst = root / "AGENTS.md"
    dst.write_text("Generated by test\nold\n", encoding="utf-8")

    apply_planned_writes(
        writes=[PlannedWrite(dst, "Generated by test\nnew\n")],
        root=root,
        generated_markers=("Generated by test",),
    )

    assert dst.read_text(encoding="utf-8") == "Generated by test\nnew\n"


def test_apply_planned_writes_force_overwrites_non_generated_file(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    dst = root / "AGENTS.md"
    dst.write_text("user notes\n", encoding="utf-8")

    apply_planned_writes(
        writes=[PlannedWrite(dst, "new content\n")],
        root=root,
        force=True,
    )

    assert dst.read_text(encoding="utf-8") == "new content\n"


def test_apply_planned_writes_refuses_path_outside_root(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    outside = tmp_path / "outside.md"

    with pytest.raises(InstallWriteError, match="outside target root"):
        apply_planned_writes(
            writes=[PlannedWrite(outside, "content\n")],
            root=root,
        )


def test_apply_planned_writes_refuses_symlink_destination(tmp_path):
    root = tmp_path / "target"
    root.mkdir()
    real = root / "real.md"
    real.write_text("real\n", encoding="utf-8")
    link = root / "link.md"
    link.symlink_to(real)

    with pytest.raises(InstallWriteError, match="symlink"):
        apply_planned_writes(
            writes=[PlannedWrite(link, "new\n")],
            root=root,
            force=True,
        )

    assert real.read_text(encoding="utf-8") == "real\n"

