"""Workspace-local runtime asset installation helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
from typing import Any

from multi_agent_brief.orchestrator_contract import is_source_repo, resolve_repo_workdir


INSTALL_MARKER = "<!-- Generated by multi-agent-brief runtime install. -->"
SKILL_NAME = "multi-agent-brief-workflow"
SUPPORTED_RUNTIMES = ("opencode", "claude")
SOURCE_CLONE_ONLY_MESSAGE = (
    "Runtime workspace kit assets are source-clone-only in this install. "
    "Run this command from a MABW source clone, or pass --repo-workdir pointing "
    "to a source repository that contains .opencode/.claude/.agents assets."
)


class RuntimeAssetInstallError(RuntimeError):
    """Raised when workspace runtime assets cannot be installed."""


@dataclass(frozen=True)
class PlannedWrite:
    destination: Path
    content: str | Path


def install_runtime_kit(
    *,
    workspace: str | Path,
    runtime: str,
    repo_workdir: str | Path | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Install runtime-discoverable assets into a user workspace."""
    ws = Path(workspace).expanduser().resolve()
    if not ws.exists() or not ws.is_dir():
        raise RuntimeAssetInstallError(f"Workspace directory not found: {ws}")

    runtimes = SUPPORTED_RUNTIMES if runtime == "all" else (runtime,)
    unknown = [name for name in runtimes if name not in SUPPORTED_RUNTIMES]
    if unknown:
        raise RuntimeAssetInstallError(f"Unsupported runtime: {', '.join(unknown)}")

    repo = _resolve_source_repo(repo_workdir=repo_workdir, workspace=ws)

    all_writes: list[PlannedWrite] = []
    for runtime_name in runtimes:
        if runtime_name == "opencode":
            all_writes.extend(_opencode_writes(workspace=ws, repo=repo))
        elif runtime_name == "claude":
            all_writes.extend(_claude_writes(workspace=ws, repo=repo))

    _validate_destinations(workspace=ws, writes=all_writes)
    _check_overwrites(writes=all_writes, force=force)

    if not dry_run:
        for write in all_writes:
            write.destination.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(write.content, Path):
                shutil.copy2(write.content, write.destination)
            else:
                write.destination.write_text(write.content, encoding="utf-8")

    return {
        "runtime": runtime,
        "workspace": str(ws),
        "repo_workdir": str(repo),
        "dry_run": dry_run,
        "written": [str(write.destination) for write in all_writes],
        "count": len(all_writes),
    }


def _resolve_source_repo(*, repo_workdir: str | Path | None, workspace: Path) -> Path:
    try:
        repo = resolve_repo_workdir(repo_workdir, workspace=workspace)
    except ValueError as exc:
        raise RuntimeAssetInstallError(SOURCE_CLONE_ONLY_MESSAGE) from exc
    if not is_source_repo(repo):
        raise RuntimeAssetInstallError(SOURCE_CLONE_ONLY_MESSAGE)
    required = [repo / ".agents" / "skills", repo / ".opencode", repo / ".claude"]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise RuntimeAssetInstallError(
            f"{SOURCE_CLONE_ONLY_MESSAGE} Missing source assets: {', '.join(missing)}"
        )
    return repo


def _opencode_writes(*, workspace: Path, repo: Path) -> list[PlannedWrite]:
    writes: list[PlannedWrite] = [
        PlannedWrite(workspace / "AGENTS.md", _workspace_agents_text("OpenCode")),
        PlannedWrite(workspace / "opencode.jsonc", _opencode_jsonc_text()),
        PlannedWrite(
            workspace / ".opencode" / "commands" / "generate-brief.md",
            _workspace_command_text(runtime="opencode"),
        ),
        PlannedWrite(
            workspace / ".opencode" / "skills" / SKILL_NAME / "SKILL.md",
            _workspace_skill_text(runtime="OpenCode"),
        ),
    ]
    writes.extend(
        PlannedWrite(workspace / ".opencode" / "agents" / src.name, _marked_source_text(src))
        for src in sorted((repo / ".opencode" / "agents").glob("*.md"))
    )
    writes.extend(_reference_writes(workspace / ".opencode" / "skills" / SKILL_NAME / "references"))
    return writes


def _claude_writes(*, workspace: Path, repo: Path) -> list[PlannedWrite]:
    writes: list[PlannedWrite] = [
        PlannedWrite(workspace / "CLAUDE.md", _workspace_agents_text("Claude Code")),
        PlannedWrite(
            workspace / ".claude" / "commands" / "generate-brief.md",
            _workspace_command_text(runtime="claude"),
        ),
        PlannedWrite(
            workspace / ".claude" / "skills" / SKILL_NAME / "SKILL.md",
            _workspace_skill_text(runtime="Claude Code"),
        ),
    ]
    writes.extend(
        PlannedWrite(workspace / ".claude" / "agents" / src.name, _marked_source_text(src))
        for src in sorted((repo / ".claude" / "agents").glob("*.md"))
    )
    writes.extend(_reference_writes(workspace / ".claude" / "skills" / SKILL_NAME / "references"))
    return writes


def _reference_writes(reference_dir: Path) -> list[PlannedWrite]:
    references = {
        "runtime-workflow.md": _runtime_workflow_reference(),
        "control-surfaces.md": _control_surfaces_reference(),
        "artifact-boundary.md": _artifact_boundary_reference(),
    }
    return [
        PlannedWrite(reference_dir / name, f"{INSTALL_MARKER}\n{text}")
        for name, text in references.items()
    ]


def _marked_source_text(path: Path) -> str:
    return f"{INSTALL_MARKER}\n{path.read_text(encoding='utf-8')}"


def _workspace_command_text(*, runtime: str) -> str:
    runtime_label = "OpenCode" if runtime == "opencode" else "Claude Code"
    frontmatter = (
        "---\n"
        "description: Generate a real source-grounded brief from this workspace\n"
    )
    if runtime == "opencode":
        frontmatter += "agent: brief-orchestrator\nsubtask: false\n"
    else:
        frontmatter += 'argument-hint: "[workspace-path]"\n'
    frontmatter += "---"
    return f"""{INSTALL_MARKER}
{frontmatter}

You are the Orchestrator main agent for this MABW workspace.

Use the current project root as the workspace when no explicit path is provided.
If a workspace path is provided, use that path instead.

First create or refresh the runtime handoff/control context:

```bash
multi-agent-brief run --workspace <workspace> --runtime {runtime} --skip-doctor
```

Then read:

- `output/intermediate/agent_handoff.md`
- `output/intermediate/agent_handoff.json`
- `output/intermediate/workflow_state.json`
- `output/intermediate/artifact_registry.json`
- `output/intermediate/audience_profile_snapshot.md`
- `output/intermediate/orchestrator_control_switchboard.json`

Read contract references from `agent_handoff.json`. Do not assume this workspace
contains the MABW source repository or `configs/` directory.

Use the installed {runtime_label} project agents/subagents when available. Keep
Python as tools, validators, audit helpers, and renderers; Python is not the
brief-generation runtime.

Selection is not execution. If you enable a control with
`multi-agent-brief controls select`, explicitly run the corresponding command
afterward when appropriate.

Before finalize, run gates/state review:

```bash
multi-agent-brief gates check --workspace <workspace>
multi-agent-brief state check --workspace <workspace> --strict
```

Only finalize after audit, gates, and state review pass:

```bash
multi-agent-brief finalize --config <workspace>/config.yaml
```
"""


def _workspace_skill_text(*, runtime: str) -> str:
    return f"""{INSTALL_MARKER}
---
name: multi-agent-brief-workflow
description: Workspace-local MABW runtime contract for {runtime}.
---

# Multi-Agent Brief Workflow Workspace Runtime Kit

This skill is installed into the business workspace so the runtime can operate
without reading the MABW source repository.

Start by running `multi-agent-brief run --workspace <workspace> --skip-doctor`,
then read the handoff files under `output/intermediate/`.

References:

- `references/runtime-workflow.md`
- `references/control-surfaces.md`
- `references/artifact-boundary.md`
"""


def _workspace_agents_text(runtime: str) -> str:
    return f"""{INSTALL_MARKER}
# MABW Workspace Runtime Instructions

This workspace has a local {runtime} runtime kit installed.

Use `multi-agent-brief run --workspace . --runtime <runtime> --skip-doctor` to
create handoff and control files before delegating role work.

Do not read the MABW source repository during normal runtime execution. Read
workspace-local handoff files and project agents/skills instead.

Python remains the setup, validation, audit, control, and rendering layer. The
external runtime Orchestrator coordinates specialist roles.
"""


def _opencode_jsonc_text() -> str:
    return f"""{INSTALL_MARKER}
{{
  // Workspace-local MABW runtime kit.
  // Agents live under .opencode/agents and the command under .opencode/commands.
  // No default_agent is forced; select brief-orchestrator explicitly if desired.
}}
"""


def _runtime_workflow_reference() -> str:
    return """# Runtime Workflow

Use `multi-agent-brief run --workspace <workspace>` as the handoff launcher.
The Orchestrator reads handoff/control files and delegates external roles:
scout, screener, claim-ledger, analyst, editor, auditor, and formatter.

The compact workflow may assign multiple stages to one runtime agent, but the
same accountable artifacts remain required.
"""


def _control_surfaces_reference() -> str:
    return """# Control Surfaces

Runtime state, feedback, quality gates, provenance projection, audience
snapshot, and control switchboard are control/context surfaces. They are not
source evidence and are not Python-executed agent stages.

Control selection records intent only. Execute selected controls explicitly.
"""


def _artifact_boundary_reference() -> str:
    return """# Artifact Boundary

Do not treat `audience_profile.md`, feedback, instructions, context documents,
or runtime control files as factual evidence.

Claim Ledger remains the source-grounded factual substrate. Final reader output
must not expose internal claim IDs, source IDs, evidence text, local paths, or
`file://` URLs.
"""


def _validate_destinations(*, workspace: Path, writes: list[PlannedWrite]) -> None:
    for write in writes:
        resolved = write.destination.resolve()
        try:
            resolved.relative_to(workspace)
        except ValueError as exc:
            raise RuntimeAssetInstallError(
                f"Runtime kit write resolves outside workspace: {write.destination}"
            ) from exc
        if write.destination.is_symlink():
            raise RuntimeAssetInstallError(
                f"Refusing to overwrite symlink during runtime kit install: {write.destination}"
            )


def _check_overwrites(*, writes: list[PlannedWrite], force: bool) -> None:
    for write in writes:
        dst = write.destination
        if not dst.exists():
            continue
        if force or _existing_is_generated(dst):
            continue
        if isinstance(write.content, Path) and dst.read_bytes() == write.content.read_bytes():
            continue
        if isinstance(write.content, str):
            try:
                if dst.read_text(encoding="utf-8") == write.content:
                    continue
            except UnicodeDecodeError:
                pass
        raise RuntimeAssetInstallError(
            f"Refusing to overwrite existing non-MABW file without --force: {dst}"
        )


def _existing_is_generated(path: Path) -> bool:
    try:
        return INSTALL_MARKER in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
