"""Workspace-local runtime asset installation helpers."""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
import os
from pathlib import Path
import stat
from typing import Any

from multi_agent_brief.install.writer import (
    InstallWriteError,
    PlannedWrite,
    apply_planned_writes,
)


INSTALL_MARKER = "<!-- Generated by multi-agent-brief runtime install. -->"
JSONC_INSTALL_MARKER = "// Generated by multi-agent-brief runtime install."
TOML_INSTALL_MARKER = "# Generated by multi-agent-brief runtime install."
SUPPORTED_RUNTIMES = ("codex", "dsh")

DSH_ROLE_IDS = (
    "source-planner",
    "source-provider",
    "scout",
    "screener",
    "claim-ledger",
    "analyst",
    "editor",
    "auditor",
)


class RuntimeAssetInstallError(RuntimeError):
    """Raised when workspace runtime assets cannot be installed."""


@dataclass(frozen=True)
class ProtectedRuntimeAssetObservation:
    """A verified runtime destination that participates only in safety checks."""

    destination: Path


@dataclass(frozen=True)
class RuntimeAssetPlan:
    """Frozen in-memory rendered plan for one or more runtime kits."""

    runtime: str
    runtimes: tuple[str, ...]
    workspace: Path
    repo_workdir: Path | None
    writes: tuple[PlannedWrite, ...]
    protected_observations: tuple[ProtectedRuntimeAssetObservation, ...] = ()


def install_runtime_kit(
    *,
    workspace: str | Path,
    runtime: str,
    repo_workdir: str | Path | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Install the packaged Codex ControlStore runtime kit into a workspace."""
    plan = plan_runtime_kit(
        workspace=workspace,
        runtime=runtime,
        repo_workdir=repo_workdir,
    )
    preflighted = preflight_runtime_kit_plans(plans=(plan,), force=force)
    return apply_runtime_kit_plan(
        preflighted,
        force=force,
        dry_run=dry_run,
    )


def plan_runtime_kit(
    *,
    workspace: str | Path,
    runtime: str,
    repo_workdir: str | Path | None = None,
) -> RuntimeAssetPlan:
    """Render one runtime selection without applying filesystem changes."""
    ws = Path(workspace).expanduser().resolve()
    if not ws.exists() or not ws.is_dir():
        raise RuntimeAssetInstallError(f"Workspace directory not found: {ws}")

    if runtime not in ("codex", "dsh", "all"):
        raise RuntimeAssetInstallError(f"Unsupported runtime: {runtime}")

    selected = SUPPORTED_RUNTIMES if runtime == "all" else (runtime,)
    all_writes: list[PlannedWrite] = []
    if "codex" in selected:
        all_writes.extend(_codex_writes(workspace=ws))
        _validate_existing_codex_kit_subset(workspace=ws, writes=all_writes)
    if "dsh" in selected:
        all_writes.extend(_dsh_writes(workspace=ws))
        _validate_existing_dsh_kit_subset(workspace=ws, writes=all_writes)
    all_writes = _deduplicate_writes(all_writes)

    return RuntimeAssetPlan(
        runtime=runtime,
        runtimes=tuple(selected),
        workspace=ws,
        repo_workdir=None,
        writes=tuple(all_writes),
    )


def preflight_runtime_kit_plans(
    *,
    plans: tuple[RuntimeAssetPlan, ...],
    force: bool,
    runtime: str | None = None,
    protected_observations: tuple[ProtectedRuntimeAssetObservation, ...] = (),
) -> RuntimeAssetPlan:
    """Validate a complete selected set of rendered plans without writing."""
    if not plans:
        raise RuntimeAssetInstallError("No runtime kit plans were selected.")

    workspace = plans[0].workspace
    if any(plan.workspace != workspace for plan in plans):
        raise RuntimeAssetInstallError("Runtime kit plans must share one workspace.")

    runtimes = tuple(runtime_name for plan in plans for runtime_name in plan.runtimes)
    combined = RuntimeAssetPlan(
        runtime=runtime or (plans[0].runtime if len(plans) == 1 else "all"),
        runtimes=runtimes,
        workspace=workspace,
        repo_workdir=next(
            (plan.repo_workdir for plan in plans if plan.repo_workdir is not None),
            None,
        ),
        writes=tuple(
            _deduplicate_writes([write for plan in plans for write in plan.writes])
        ),
        protected_observations=tuple(
            _deduplicate_protected_observations(
                [
                    observation
                    for plan in plans
                    for observation in plan.protected_observations
                ]
                + list(protected_observations)
            )
        ),
    )
    _validate_runtime_kit_plan(combined, force=force)
    return combined


def apply_runtime_kit_plan(
    plan: RuntimeAssetPlan,
    *,
    force: bool,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Apply already-rendered writes, rechecking safety immediately before use."""

    _validate_runtime_kit_destination_topology(plan)
    try:
        apply_planned_writes(
            writes=list(plan.writes),
            root=plan.workspace,
            force=force,
            dry_run=dry_run,
            generated_markers=(
                INSTALL_MARKER,
                JSONC_INSTALL_MARKER,
                TOML_INSTALL_MARKER,
            ),
        )
    except InstallWriteError as exc:
        raise RuntimeAssetInstallError(str(exc)) from exc

    if "codex" in plan.runtimes and not dry_run:
        _verify_materialized_codex_runtime_kit(plan.workspace)
    if "dsh" in plan.runtimes and not dry_run:
        _verify_materialized_dsh_runtime_kit(plan.workspace)

    return {
        "runtime": plan.runtime,
        "workspace": str(plan.workspace),
        "repo_workdir": (None if plan.repo_workdir is None else str(plan.repo_workdir)),
        "dry_run": dry_run,
        "written": [str(write.destination) for write in plan.writes],
        "count": len(plan.writes),
    }


def _validate_runtime_kit_plan(plan: RuntimeAssetPlan, *, force: bool) -> None:
    """Run the shared writer's complete safety checks with zero writes."""
    _validate_runtime_kit_destination_topology(plan)
    try:
        apply_planned_writes(
            writes=list(plan.writes),
            root=plan.workspace,
            force=force,
            dry_run=True,
            generated_markers=(
                INSTALL_MARKER,
                JSONC_INSTALL_MARKER,
                TOML_INSTALL_MARKER,
            ),
        )
    except InstallWriteError as exc:
        raise RuntimeAssetInstallError(str(exc)) from exc


def _validate_runtime_kit_destination_topology(plan: RuntimeAssetPlan) -> None:
    """Reject unmaterializable destination ancestry before any selected write."""

    writable_destinations = [write.destination for write in plan.writes]
    protected_destinations = [
        observation.destination for observation in plan.protected_observations
    ]
    protected_set = set(protected_destinations)
    for destination in writable_destinations:
        if destination in protected_set:
            raise RuntimeAssetInstallError(
                "Conflicting protected Codex and writable runtime destinations: "
                f"{destination}"
            )

    _validate_planned_destination_graph(
        [*protected_destinations, *writable_destinations]
    )
    protected_leaves: dict[tuple[int, int], Path] = {}
    for destination in protected_destinations:
        identity = _validate_destination_ancestry(
            workspace=plan.workspace,
            destination=destination,
        )
        if identity is not None:
            protected_leaves.setdefault(identity, destination)

    writable_leaves: dict[tuple[int, int], Path] = {}
    for destination in writable_destinations:
        identity = _validate_destination_ancestry(
            workspace=plan.workspace,
            destination=destination,
        )
        if identity is None:
            continue
        protected = protected_leaves.get(identity)
        if protected is not None:
            raise RuntimeAssetInstallError(
                "Conflicting protected Codex and writable runtime destinations: "
                f"{protected} and {destination}"
            )
        existing = writable_leaves.setdefault(identity, destination)
        if existing != destination:
            raise RuntimeAssetInstallError(
                "Conflicting aliased runtime install destinations: "
                f"{existing} and {destination}"
            )


def _validate_planned_destination_graph(destinations: list[Path]) -> None:
    """Reject a planned file that would also need to be another file's parent."""

    for index, destination in enumerate(destinations):
        for other in destinations[index + 1 :]:
            if _is_descendant_path(other, destination):
                raise RuntimeAssetInstallError(
                    "Conflicting runtime install destination ancestry: "
                    f"{destination} is a parent of {other}"
                )
            if _is_descendant_path(destination, other):
                raise RuntimeAssetInstallError(
                    "Conflicting runtime install destination ancestry: "
                    f"{other} is a parent of {destination}"
                )


def _is_descendant_path(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return path != parent


def _validate_destination_ancestry(
    *,
    workspace: Path,
    destination: Path,
) -> tuple[int, int] | None:
    """Classify every existing parent and leaf without following symlinks."""

    try:
        relative = destination.relative_to(workspace)
    except ValueError:
        # The shared writer owns the existing resolved-containment error.
        return None

    ancestor = workspace
    for component in relative.parts[:-1]:
        ancestor = ancestor / component
        metadata = _runtime_asset_lstat(ancestor)
        if metadata is None:
            break
        if stat.S_ISLNK(metadata.st_mode):
            raise RuntimeAssetInstallError(
                f"Refusing to use symlinked runtime install ancestor: {ancestor}"
            )
        if not stat.S_ISDIR(metadata.st_mode):
            raise RuntimeAssetInstallError(
                f"Refusing to use non-directory runtime install ancestor: {ancestor}"
            )

    leaf_metadata = _runtime_asset_lstat(destination)
    if leaf_metadata is None:
        return None
    if stat.S_ISLNK(leaf_metadata.st_mode):
        raise RuntimeAssetInstallError(
            f"Refusing to use symlinked runtime install destination: {destination}"
        )
    if stat.S_ISDIR(leaf_metadata.st_mode):
        raise RuntimeAssetInstallError(
            f"Refusing to overwrite directory during runtime install: {destination}"
        )
    if not stat.S_ISREG(leaf_metadata.st_mode):
        raise RuntimeAssetInstallError(
            f"Refusing to overwrite non-regular runtime install destination: {destination}"
        )

    return (leaf_metadata.st_dev, leaf_metadata.st_ino)


def _runtime_asset_lstat(path: Path) -> os.stat_result | None:
    try:
        return path.lstat()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise RuntimeAssetInstallError(
            f"Unable to inspect runtime install destination: {path}"
        ) from exc


def _validate_existing_codex_kit_subset(
    *,
    workspace: Path,
    writes: list[PlannedWrite],
) -> None:
    """Allow only an exact, resumable subset of the packaged Codex kit."""

    kit_root = workspace / ".codex"
    expected: dict[str, bytes] = {}
    for write in writes:
        try:
            relative = write.destination.relative_to(kit_root).as_posix()
        except ValueError:
            continue
        expected[relative] = write.content.encode("utf-8")
    expected_directories = {
        parent.as_posix()
        for relative in expected
        for parent in Path(relative).parents
        if parent != Path(".")
    }

    try:
        root_mode = kit_root.lstat().st_mode
    except FileNotFoundError:
        return
    except OSError as exc:
        raise _codex_existing_content_error(exc)
    if not stat.S_ISDIR(root_mode):
        raise _codex_existing_content_error()

    pending = [kit_root]
    while pending:
        directory = pending.pop()
        try:
            entries = list(os.scandir(directory))
        except OSError as exc:
            raise _codex_existing_content_error(exc)
        for entry in entries:
            relative = Path(entry.path).relative_to(kit_root).as_posix()
            try:
                if entry.is_symlink():
                    raise _codex_existing_content_error()
                if entry.is_dir(follow_symlinks=False):
                    if relative not in expected_directories:
                        raise _codex_existing_content_error()
                    pending.append(Path(entry.path))
                    continue
                if not entry.is_file(follow_symlinks=False):
                    raise _codex_existing_content_error()
                expected_bytes = expected.get(relative)
                if (
                    expected_bytes is None
                    or Path(entry.path).read_bytes() != expected_bytes
                ):
                    raise _codex_existing_content_error()
            except RuntimeAssetInstallError:
                raise
            except OSError as exc:
                raise _codex_existing_content_error(exc)


def _codex_existing_content_error(
    exc: BaseException | None = None,
) -> RuntimeAssetInstallError:
    error = RuntimeAssetInstallError(
        "Workspace Codex runtime kit contains non-generated or mismatched content."
    )
    if exc is not None:
        error.__cause__ = exc
    return error


def _verify_materialized_codex_runtime_kit(workspace: Path) -> None:
    from multi_agent_brief.runtime_host_v2.codex import (
        load_codex_adapter_binding,
        load_workspace_codex_adapter_binding,
    )
    from multi_agent_brief.runtime_host_v2.errors import RuntimeHostError

    verification_run_id = "RUN-CODEX-KIT-VERIFY"
    try:
        workspace_binding = load_workspace_codex_adapter_binding(
            workspace,
            verification_run_id,
        )
        packaged_binding = load_codex_adapter_binding(verification_run_id)
    except RuntimeHostError as exc:
        raise RuntimeAssetInstallError(
            "Installed Codex runtime kit failed exact verification."
        ) from exc
    if workspace_binding != packaged_binding:
        raise RuntimeAssetInstallError(
            "Installed Codex runtime kit failed exact verification."
        )


def _deduplicate_writes(writes: list[PlannedWrite]) -> list[PlannedWrite]:
    unique: list[PlannedWrite] = []
    by_destination: dict[Path, PlannedWrite] = {}
    for write in writes:
        existing = by_destination.get(write.destination)
        if existing is None:
            by_destination[write.destination] = write
            unique.append(write)
            continue
        if existing.content != write.content:
            raise RuntimeAssetInstallError(
                f"Conflicting generated runtime asset content for {write.destination}"
            )
    return unique


def _deduplicate_protected_observations(
    observations: list[ProtectedRuntimeAssetObservation],
) -> list[ProtectedRuntimeAssetObservation]:
    unique: list[ProtectedRuntimeAssetObservation] = []
    seen: set[Path] = set()
    for observation in observations:
        if observation.destination in seen:
            continue
        seen.add(observation.destination)
        unique.append(observation)
    return unique



def _codex_asset(relative: str) -> str:
    try:
        return (
            resources.files("multi_agent_brief")
            .joinpath("runtime_kits", "codex", *relative.split("/"))
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, OSError) as exc:
        raise RuntimeAssetInstallError(
            "Packaged Codex ControlStore runtime kit is unavailable."
        ) from exc


def _codex_writes(*, workspace: Path) -> list[PlannedWrite]:
    role_ids = (
        "source-planner",
        "source-provider",
        "scout",
        "screener",
        "claim-ledger",
        "analyst",
        "editor",
        "auditor",
    )
    return [
        PlannedWrite(
            workspace / ".codex" / "config.toml",
            _codex_asset("config.toml"),
        ),
        PlannedWrite(
            workspace / ".codex" / "skills" / "briefloop" / "SKILL.md",
            _codex_asset("skills/briefloop/SKILL.md"),
        ),
        PlannedWrite(
            workspace
            / ".codex"
            / "skills"
            / "briefloop"
            / "references"
            / "controlstore-v2.md",
            _codex_asset("skills/briefloop/references/controlstore-v2.md"),
        ),
        *(
            PlannedWrite(
                workspace / ".codex" / "agents" / f"briefloop-{role_id}.toml",
                _codex_asset(f"agents/briefloop-{role_id}.toml"),
            )
            for role_id in role_ids
        ),
    ]


def plan_protected_codex_observations(
    *,
    workspace: str | Path,
) -> tuple[ProtectedRuntimeAssetObservation, ...]:
    """Project the packaged Codex kit into read-only topology observations."""

    resolved_workspace = Path(workspace).expanduser().resolve()
    return tuple(
        ProtectedRuntimeAssetObservation(destination=write.destination)
        for write in _codex_writes(workspace=resolved_workspace)
    )


def _dsh_asset(relative: str) -> str:
    try:
        return (
            resources.files("multi_agent_brief")
            .joinpath("runtime_kits", "dsh", *relative.split("/"))
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, OSError) as exc:
        raise RuntimeAssetInstallError(
            "Packaged DeepSeek Harness runtime kit is unavailable."
        ) from exc


def _dsh_writes(*, workspace: Path) -> list[PlannedWrite]:
    return [
        PlannedWrite(
            workspace / ".dsh" / "README.md",
            _dsh_asset("README.md"),
        ),
        PlannedWrite(
            workspace / ".dsh" / "plugin" / "briefloop-dsh.host.js",
            _dsh_asset("plugin/briefloop-dsh.host.js"),
        ),
        PlannedWrite(
            workspace / ".dsh" / "skills" / "briefloop" / "SKILL.md",
            _dsh_asset("skills/briefloop/SKILL.md"),
        ),
        PlannedWrite(
            workspace
            / ".dsh"
            / "skills"
            / "briefloop"
            / "references"
            / "controlstore-v2.md",
            _dsh_asset("skills/briefloop/references/controlstore-v2.md"),
        ),
        *(
            PlannedWrite(
                workspace
                / ".dsh"
                / "presets"
                / f"briefloop-{role_id}"
                / "agent.cordis.yml",
                _dsh_asset(f"presets/briefloop-{role_id}/agent.cordis.yml"),
            )
            for role_id in DSH_ROLE_IDS
        ),
        *(
            PlannedWrite(
                workspace
                / ".dsh"
                / "presets"
                / f"briefloop-{role_id}"
                / "preset.yml",
                _dsh_asset(f"presets/briefloop-{role_id}/preset.yml"),
            )
            for role_id in DSH_ROLE_IDS
        ),
    ]


def _validate_existing_dsh_kit_subset(
    *,
    workspace: Path,
    writes: list[PlannedWrite],
) -> None:
    """Allow only an exact, resumable subset of the packaged DSH kit."""

    kit_root = workspace / ".dsh"
    expected: dict[str, bytes] = {}
    for write in writes:
        try:
            relative = write.destination.relative_to(kit_root).as_posix()
        except ValueError:
            continue
        expected[relative] = write.content.encode("utf-8")
    expected_directories = {
        parent.as_posix()
        for relative in expected
        for parent in Path(relative).parents
        if parent != Path(".")
    }

    try:
        root_mode = kit_root.lstat().st_mode
    except FileNotFoundError:
        return
    except OSError as exc:
        raise _dsh_existing_content_error(exc)
    if not stat.S_ISDIR(root_mode):
        raise _dsh_existing_content_error()

    pending = [kit_root]
    while pending:
        directory = pending.pop()
        try:
            entries = list(os.scandir(directory))
        except OSError as exc:
            raise _dsh_existing_content_error(exc)
        for entry in entries:
            relative = Path(entry.path).relative_to(kit_root).as_posix()
            try:
                if entry.is_symlink():
                    raise _dsh_existing_content_error()
                if entry.is_dir(follow_symlinks=False):
                    if relative not in expected_directories:
                        raise _dsh_existing_content_error()
                    pending.append(Path(entry.path))
                    continue
                if not entry.is_file(follow_symlinks=False):
                    raise _dsh_existing_content_error()
                expected_bytes = expected.get(relative)
                if (
                    expected_bytes is None
                    or Path(entry.path).read_bytes() != expected_bytes
                ):
                    raise _dsh_existing_content_error()
            except RuntimeAssetInstallError:
                raise
            except OSError as exc:
                raise _dsh_existing_content_error(exc)


def _dsh_existing_content_error(
    exc: BaseException | None = None,
) -> RuntimeAssetInstallError:
    error = RuntimeAssetInstallError(
        "Workspace DeepSeek Harness runtime kit contains non-generated or mismatched content."
    )
    if exc is not None:
        error.__cause__ = exc
    return error


def _verify_materialized_dsh_runtime_kit(workspace: Path) -> None:
    from multi_agent_brief.runtime_host_v2.dsh import (
        load_dsh_adapter_binding,
        load_workspace_dsh_adapter_binding,
    )
    from multi_agent_brief.runtime_host_v2.errors import RuntimeHostError

    verification_run_id = "RUN-DSH-KIT-VERIFY"
    try:
        workspace_binding = load_workspace_dsh_adapter_binding(
            workspace,
            verification_run_id,
        )
        packaged_binding = load_dsh_adapter_binding(verification_run_id)
    except RuntimeHostError as exc:
        raise RuntimeAssetInstallError(
            "Installed DeepSeek Harness runtime kit failed exact verification."
        ) from exc
    if workspace_binding != packaged_binding:
        raise RuntimeAssetInstallError(
            "Installed DeepSeek Harness runtime kit failed exact verification."
        )


def plan_protected_dsh_observations(
    *,
    workspace: str | Path,
) -> tuple[ProtectedRuntimeAssetObservation, ...]:
    """Project the packaged DSH kit into read-only topology observations."""

    resolved_workspace = Path(workspace).expanduser().resolve()
    return tuple(
        ProtectedRuntimeAssetObservation(destination=write.destination)
        for write in _dsh_writes(workspace=resolved_workspace)
    )
