"""Workspace-local runtime asset installation helpers."""

from __future__ import annotations

from importlib import resources
import os
from pathlib import Path
import stat
from typing import Any

from multi_agent_brief.install.writer import (
    InstallWriteError,
    PlannedWrite,
    apply_planned_writes,
)


INSTALL_MARKER = "<!-- Generated by multi-agent-brief runtime install. -->"
JSONC_INSTALL_MARKER = "// Generated by multi-agent-brief runtime install."
TOML_INSTALL_MARKER = "# Generated by multi-agent-brief runtime install."
SUPPORTED_RUNTIMES = ("codex",)


class RuntimeAssetInstallError(RuntimeError):
    """Raised when workspace runtime assets cannot be installed."""


def install_runtime_kit(
    *,
    workspace: str | Path,
    runtime: str,
    repo_workdir: str | Path | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Install the packaged Codex ControlStore runtime kit into a workspace."""
    ws = Path(workspace).expanduser().resolve()
    if not ws.exists() or not ws.is_dir():
        raise RuntimeAssetInstallError(f"Workspace directory not found: {ws}")

    if runtime not in ("codex", "all"):
        raise RuntimeAssetInstallError(f"Unsupported runtime: {runtime}")

    all_writes = _codex_writes(workspace=ws)
    all_writes = _deduplicate_writes(all_writes)
    _validate_existing_codex_kit_subset(workspace=ws, writes=all_writes)

    try:
        apply_planned_writes(
            writes=all_writes,
            root=ws,
            force=force,
            dry_run=dry_run,
            generated_markers=(
                INSTALL_MARKER,
                JSONC_INSTALL_MARKER,
                TOML_INSTALL_MARKER,
            ),
        )
    except InstallWriteError as exc:
        raise RuntimeAssetInstallError(str(exc)) from exc

    if not dry_run:
        _verify_materialized_codex_runtime_kit(ws)

    return {
        "runtime": runtime,
        "workspace": str(ws),
        "repo_workdir": None,
        "dry_run": dry_run,
        "written": [str(write.destination) for write in all_writes],
        "count": len(all_writes),
    }


def _validate_existing_codex_kit_subset(
    *,
    workspace: Path,
    writes: list[PlannedWrite],
) -> None:
    """Allow only an exact, resumable subset of the packaged Codex kit."""

    kit_root = workspace / ".codex"
    expected: dict[str, bytes] = {}
    for write in writes:
        try:
            relative = write.destination.relative_to(kit_root).as_posix()
        except ValueError:
            continue
        expected[relative] = write.content.encode("utf-8")
    expected_directories = {
        parent.as_posix()
        for relative in expected
        for parent in Path(relative).parents
        if parent != Path(".")
    }

    try:
        root_mode = kit_root.lstat().st_mode
    except FileNotFoundError:
        return
    except OSError as exc:
        raise _codex_existing_content_error(exc)
    if not stat.S_ISDIR(root_mode):
        raise _codex_existing_content_error()

    pending = [kit_root]
    while pending:
        directory = pending.pop()
        try:
            entries = list(os.scandir(directory))
        except OSError as exc:
            raise _codex_existing_content_error(exc)
        for entry in entries:
            relative = Path(entry.path).relative_to(kit_root).as_posix()
            try:
                if entry.is_symlink():
                    raise _codex_existing_content_error()
                if entry.is_dir(follow_symlinks=False):
                    if relative not in expected_directories:
                        raise _codex_existing_content_error()
                    pending.append(Path(entry.path))
                    continue
                if not entry.is_file(follow_symlinks=False):
                    raise _codex_existing_content_error()
                expected_bytes = expected.get(relative)
                if (
                    expected_bytes is None
                    or Path(entry.path).read_bytes() != expected_bytes
                ):
                    raise _codex_existing_content_error()
            except RuntimeAssetInstallError:
                raise
            except OSError as exc:
                raise _codex_existing_content_error(exc)


def _codex_existing_content_error(
    exc: BaseException | None = None,
) -> RuntimeAssetInstallError:
    error = RuntimeAssetInstallError(
        "Workspace Codex runtime kit contains non-generated or mismatched content."
    )
    if exc is not None:
        error.__cause__ = exc
    return error


def _verify_materialized_codex_runtime_kit(workspace: Path) -> None:
    from multi_agent_brief.runtime_host_v2.codex import (
        load_codex_adapter_binding,
        load_workspace_codex_adapter_binding,
    )
    from multi_agent_brief.runtime_host_v2.errors import RuntimeHostError

    verification_run_id = "RUN-CODEX-KIT-VERIFY"
    try:
        workspace_binding = load_workspace_codex_adapter_binding(
            workspace,
            verification_run_id,
        )
        packaged_binding = load_codex_adapter_binding(verification_run_id)
    except RuntimeHostError as exc:
        raise RuntimeAssetInstallError(
            "Installed Codex runtime kit failed exact verification."
        ) from exc
    if workspace_binding != packaged_binding:
        raise RuntimeAssetInstallError(
            "Installed Codex runtime kit failed exact verification."
        )


def _deduplicate_writes(writes: list[PlannedWrite]) -> list[PlannedWrite]:
    unique: list[PlannedWrite] = []
    by_destination: dict[Path, PlannedWrite] = {}
    for write in writes:
        existing = by_destination.get(write.destination)
        if existing is None:
            by_destination[write.destination] = write
            unique.append(write)
            continue
        if existing.content != write.content:
            raise RuntimeAssetInstallError(
                f"Conflicting generated runtime asset content for {write.destination}"
            )
    return unique


def _codex_asset(relative: str) -> str:
    try:
        return (
            resources.files("multi_agent_brief")
            .joinpath("runtime_kits", "codex", *relative.split("/"))
            .read_text(encoding="utf-8")
        )
    except (FileNotFoundError, OSError) as exc:
        raise RuntimeAssetInstallError(
            "Packaged Codex ControlStore runtime kit is unavailable."
        ) from exc


def _codex_writes(*, workspace: Path) -> list[PlannedWrite]:
    role_ids = (
        "source-planner",
        "source-provider",
        "scout",
        "screener",
        "claim-ledger",
        "analyst",
        "editor",
        "auditor",
    )
    return [
        PlannedWrite(
            workspace / ".codex" / "config.toml",
            _codex_asset("config.toml"),
        ),
        PlannedWrite(
            workspace / ".codex" / "skills" / "briefloop" / "SKILL.md",
            _codex_asset("skills/briefloop/SKILL.md"),
        ),
        PlannedWrite(
            workspace
            / ".codex"
            / "skills"
            / "briefloop"
            / "references"
            / "controlstore-v2.md",
            _codex_asset("skills/briefloop/references/controlstore-v2.md"),
        ),
        *(
            PlannedWrite(
                workspace / ".codex" / "agents" / f"briefloop-{role_id}.toml",
                _codex_asset(f"agents/briefloop-{role_id}.toml"),
            )
            for role_id in role_ids
        ),
    ]
