#!/usr/bin/env python3
"""Regenerate the desktop backend's hash-locked dependency list (#851).

The desktop App installs BriefLoop into its own venv on the user's Python. The
wheel is pinned by hash, but its dependencies were ranges, so two users of one
release could get different versions and every update asked PyPI again. This
lock pins every dependency with the hashes of all its published wheels for
every supported Python and platform. Run it whenever pyproject.toml's
dependencies change, and review the diff; prepare-backend.py refuses a stale lock.

  python desktop/electron/scripts/lock-backend.py      # needs uv
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[3]
LOCK = ROOT / 'desktop' / 'electron' / 'backend-requirements.txt'
MARKER = '# pyproject-dependencies-sha256: '


def dependencies_digest(root: Path = ROOT) -> str:
    project = tomllib.loads((root / 'pyproject.toml').read_text(encoding='utf-8'))
    return hashlib.sha256(json.dumps(sorted(project['project']['dependencies'])).encode()).hexdigest()


def locked_digest(lock: Path = LOCK) -> str | None:
    for line in lock.read_text(encoding='utf-8').splitlines():
        if line.startswith(MARKER):
            return line[len(MARKER):].strip()
    return None


def main() -> None:
    project = tomllib.loads((ROOT / 'pyproject.toml').read_text(encoding='utf-8'))
    minimum = project['project'].get('requires-python', '>=3.11').lstrip('>=').strip()
    with tempfile.TemporaryDirectory() as temporary:
        output = Path(temporary) / 'lock.txt'
        # Universal: one file for macOS and Windows, every supported Python;
        # wheels only, so no user machine ever builds from source.
        subprocess.run(['uv', 'pip', 'compile', str(ROOT / 'pyproject.toml'), '--universal', '--generate-hashes',
                        '--python-version', minimum, '--only-binary', ':all:', '--no-header',
                        '--index-url', 'https://pypi.org/simple', '-q', '-o', str(output)], check=True, cwd=ROOT)
        body = output.read_text(encoding='utf-8')
    LOCK.write_text('# BriefLoop desktop backend dependencies, pinned with hashes for every wheel.\n'
                    '# Generated by desktop/electron/scripts/lock-backend.py; do not edit by hand.\n'
                    f'{MARKER}{dependencies_digest()}\n{body}', encoding='utf-8', newline='\n')
    print(f'Wrote {LOCK.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
