#!/usr/bin/env python3
"""Generate platform-specific agent adapter files from configs/agent_roles.yaml.

This script generates platform adapter files only. AGENTS.md and .agents/skills/
are hand-maintained operating contracts, not generated prompt projections.

Usage:
    python scripts/generate_agent_configs.py --write
    python scripts/generate_agent_configs.py --check
    python scripts/generate_agent_configs.py --target codex --write
    python scripts/generate_agent_configs.py --target docs --write
"""
from __future__ import annotations

import argparse
import json
import textwrap
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:
    yaml = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "configs" / "agent_roles.yaml"

AUTOGEN_HEADER_MD = "<!-- AUTO-GENERATED by scripts/generate_agent_configs.py. Edit configs/agent_roles.yaml instead. -->"
AUTOGEN_HEADER_TOML = "# AUTO-GENERATED by scripts/generate_agent_configs.py. Edit configs/agent_roles.yaml instead."

PIPELINE_TEXT = (
    "Default: Scout (discover + screen) -> Claim Ledger -> Analyst -> Delivery Editor -> Auditor -> Formatter\n"
    "Strict: Scout -> Screener -> Claim Ledger -> Analyst -> Delivery Editor -> Auditor -> Formatter"
)
HARNESS_TEXT = "draft facts pass -> final text quality pass -> rendered document quality pass -> delivery allowed"
ORCHESTRATOR_LOOP_TEXT = (
    "Read workspace context -> read contract references -> identify next stage -> "
    "delegate specialist -> check expected artifact -> decide continue / retry_stage / "
    "delegate_repair / request_human_review / block_run / finalize"
)

TARGETS = {"codex", "docs"}
PACKAGED_CODEX_ROLE_IDS = (
    "source-planner",
    "source-provider",
    "scout",
    "screener",
    "claim-ledger",
    "analyst",
    "editor",
    "auditor",
)

SENSITIVE_PATTERNS = [
    "api_key", "password",
]

SENSITIVE_CONTEXT_PATTERNS = [
    "credential", "token", "webhook", "private path", "customer name",
    "internal report", "secret",
]

# Lines containing these guardrail phrases are allowed to mention sensitive words
SENSITIVE_EXEMPTIONS = [
    "do not commit", "do not store", "do not expose", "do not put",
    "do not place", "do not import", "do not migrate", "do not copy",
    "do not save", "do not include", "do not provide", "must not",
]


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------

def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    if yaml is None:
        raise RuntimeError("PyYAML is required. Install with: pip install pyyaml")
    text = path.read_text(encoding="utf-8")
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError(f"Manifest must be a YAML mapping: {path}")
    return data


def validate_manifest(manifest: dict[str, Any]) -> None:
    required_top = ["schema_version", "project", "tool_profiles", "roles"]
    for key in required_top:
        if key not in manifest:
            raise ValueError(f"Manifest missing top-level key: {key}")

    project = manifest["project"]
    pipeline = project.get("pipeline", [])
    expected_pipeline = ["scout", "screener", "claim-ledger", "analyst", "editor", "auditor", "formatter"]
    if pipeline != expected_pipeline:
        raise ValueError(f"Subagent workflow mismatch: got {pipeline}, expected {expected_pipeline}")

    roles = manifest["roles"]
    required_fields = ["stage", "tool_profile", "description", "trigger", "responsibilities", "hard_rules"]
    for name, role in roles.items():
        for field in required_fields:
            if field not in role:
                raise ValueError(f"Role '{name}' missing field: {field}")
        tp = role["tool_profile"]
        if tp not in manifest["tool_profiles"]:
            raise ValueError(f"Role '{name}' references unknown tool_profile: {tp}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _join_lines(items: list[str], indent: str = "- ") -> str:
    return "\n".join(f"{indent}{item}" for item in items)


def _sensitive_check(text: str, context: str) -> list[str]:
    """Check for actual sensitive content (not safety-rule mentions)."""
    hits = []
    for line in text.splitlines():
        lower = line.lower()
        # Skip lines that are guardrails (may mention sensitive terms)
        if any(exempt in lower for exempt in SENSITIVE_EXEMPTIONS):
            continue
        for pattern in SENSITIVE_PATTERNS + SENSITIVE_CONTEXT_PATTERNS:
            if pattern in lower:
                hits.append(f"{context}: contains '{pattern}'")
                break
    return hits


def _toml_basic_string(value: str) -> str:
    """Render a TOML basic string."""
    return json.dumps(value, ensure_ascii=False)


def _toml_literal_multiline_string(value: str) -> str:
    """Render a TOML literal multiline string.

    Codex agent instructions intentionally contain Windows paths such as
    `.\\scripts\\setup.ps1`; TOML basic multiline strings would parse those
    backslashes as escapes. Literal strings keep the instructions byte-for-byte.
    """
    if "'''" in value:
        raise ValueError("Codex developer_instructions cannot contain TOML literal string delimiter.")
    return "'''\n" + value.rstrip() + "\n'''"


# ---------------------------------------------------------------------------
# Codex config.toml
# ---------------------------------------------------------------------------

def render_codex_config(manifest: dict) -> str:
    return textwrap.dedent(f"""\
        {AUTOGEN_HEADER_TOML}

        [agents]
        max_threads = 6
        max_depth = 1
    """)


# ---------------------------------------------------------------------------
# Codex agent TOML
# ---------------------------------------------------------------------------

def render_packaged_codex_agent(role_name: str, role: dict) -> str:
    description = _toml_basic_string(str(role["description"]))
    instructions = (
        f"You are the BriefLoop {role_name} specialist for the SQLite-only "
        "ControlStore v2 runtime.\n\n"
        "Read the exact RoleTaskEnvelope supplied by the host. Treat its "
        "run, invocation, action, role, stage, scratch directory, filenames "
        "and proposal schema as binding. Write only the listed proposal "
        "files under that invocation scratch directory. Do not write SQLite, "
        "receipts, stage state, gates, frozen artifacts, projections, config, "
        "sources, runtime files or another invocation's scratch. Do not call "
        "stage, gate, finalize, repair, approval or delivery transactions. "
        "When task_instructions name `briefloop contract show` and "
        "`briefloop runtime invocation-validate` preflight commands, run them exactly "
        "before returning; do not guess JSON wrappers, aliases, or fields. "
        "Return control to the root host after the proposal is complete.\n\n"
        "Role responsibilities:\n"
        f"{_join_lines([str(item) for item in role['responsibilities']])}\n\n"
        "Role hard rules:\n"
        f"{_join_lines([str(item) for item in role['hard_rules']])}"
    )
    return (
        f"{AUTOGEN_HEADER_TOML}\n\n"
        f'name = "{role_name}"\n'
        f"description = {description}\n"
        f"developer_instructions = "
        f"{_toml_literal_multiline_string(instructions)}\n"
    )
def render_docs(manifest: dict) -> dict[str, str]:
    roles = manifest["roles"]
    project = manifest["project"]

    # docs/agents/README.md
    role_list = "\n".join(
        f"- **{name}** ({role['stage']}): {role['description']}"
        for name, role in roles.items()
    )
    readme = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Agent Configuration

        This directory documents the cross-platform agent adapter layer for `multi-agent-brief-workflow`.

        ## Source of Truth

        Platform adapter files are generated from a single manifest:

        ```text
        configs/agent_roles.yaml
        ```

        Edit the manifest and regenerate to update platform adapter files.

        ## Generation

        ```bash
        python scripts/generate_agent_configs.py --write
        python scripts/generate_agent_configs.py --check
        ```

        Windows (PowerShell):

        ```powershell
        python scripts/generate_agent_configs.py --write
        python scripts/generate_agent_configs.py --check
        ```

        ## Subagent workflow

        ```text
        {PIPELINE_TEXT}
        ```

        ## Roles

        {role_list}

        ## Platform Files

        | Platform | Location | Format |
        |----------|----------|--------|
        | Packaged Codex runtime kit | `src/multi_agent_brief/runtime_kits/codex/` | TOML |
        | Skills | `.agents/skills/*/SKILL.md` | Markdown + YAML frontmatter, hand-maintained |
        | Project instructions | `AGENTS.md` | Markdown, hand-maintained |
    """)

    # docs/agents/codex.md
    codex_roles = "\n".join(
        f"- `briefloop-{name}.toml` — {roles[name]['description']}"
        for name in PACKAGED_CODEX_ROLE_IDS
    )
    codex = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Codex Agent Configuration

        ## Packaged Runtime Kit

        The active Codex ControlStore runtime kit lives in
        `src/multi_agent_brief/runtime_kits/codex/` and is installed into
        workspaces by `briefloop runtime install --runtime codex`. Its agent
        inventory is hash-bound into the Store adapter binding.

        {codex_roles}

        Each agent TOML file includes:

        - `name`
        - `description`
        - `developer_instructions`

        ## Skills

        Located in `.agents/skills/*/SKILL.md`.

        Skills are hand-maintained because they are runtime prompts, not simple platform config projections.

        ## Config

        `config.toml` sets:

        ```toml
        max_threads = 6
        max_depth = 1
        ```
    """)

    # docs/agents/harness-subagents.md
    harness = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Harness Subagents

        This project has two harness layers.

        ## 1. Draft Audit Harness

        Purpose:

        ```text
        auditor subagent -> CompositeAuditAgent -> DeterministicAuditAgent -> QualityHarnessAuditAgent -> optional semantic audit adapter
        ```

        Responsible subagent:

        ```text
        draft-audit-harness
        ```

        It reviews and implements:

        * missing or orphan claim IDs
        * number/source coverage
        * reporting-window freshness
        * missing source dates
        * placeholders
        * internal workflow residue
        * process residue
        * metadata residue
        * unsupported certainty wording
        * investment-advice style language
        * needs_recrawl leakage
        * T5 or low-confidence source leakage
        * low numeric source density
        * possible unit inflation
        * repeat/background claims in executive summary
        * stale/no-update filler

        ## 2. Final Delivery Harness

        Purpose:

        ```text
        {HARNESS_TEXT}
        ```

        Responsible subagents:

        ```text
        final-quality-harness
        rendered-output-harness
        ```

        `final-quality-harness` checks:

        * final report depth
        * quiet_week handling
        * front-page metadata
        * stale-current framing
        * executive summary bullet separation
        * internal workflow residue
        * publication readiness

        `rendered-output-harness` checks:

        * DOCX/PDF rendering depth
        * heading mapping
        * bullet separation after rendering
        * footer/page fields
        * margins
        * wide table conversion
        * missing rendering dependencies

        ## Rule

        Correct facts are necessary but not sufficient for final delivery. A report can pass source audit and still be blocked by final-quality or rendered-output gates.
    """)

    # docs/agents/manifest.md
    pipeline_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "pipeline"
    )
    harness_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "harness"
    )
    coord_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "coordination"
    )
    manifest_doc = (
        f"{AUTOGEN_HEADER_MD}\n"
        f"\n"
        f"# Agent Roles Manifest\n"
        f"\n"
        f"## Schema\n"
        f"\n"
        f"```text\n"
        f"configs/agent_roles.yaml\n"
        f"```\n"
        f"\n"
        f"Schema version: `{manifest['schema_version']}`\n"
        f"\n"
        f"## Structure\n"
        f"\n"
        f"```yaml\n"
        f'schema_version: "..."\n'
        f"project:\n"
        f'  name: "..."\n'
        f'  purpose: "..."\n'
        f"  workflow: [...]\n"
        f"  output_contract: [...]\n"
        f"  non_goals: [...]\n"
        f"tool_profiles:\n"
        f"  read_only: {{ ... }}\n"
        f"  edit_safe: {{ ... }}\n"
        f"  audit_read_only: {{ ... }}\n"
        f"  audit_edit: {{ ... }}\n"
        f"roles:\n"
        f"  <role-name>:\n"
        f"    stage: workflow | harness | coordination\n"
        f"    tool_profile: <profile-name>\n"
        f'    description: "..."\n'
        f'    trigger: "..."\n'
        f"    responsibilities: [...]\n"
        f"    hard_rules: [...]\n"
        f"```\n"
        f"\n"
        f"## Subagent workflow\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"## Subagent workflow Roles\n"
        f"\n"
        f"{pipeline_roles}\n"
        f"\n"
        f"## Harness Roles\n"
        f"\n"
        f"{harness_roles}\n"
        f"\n"
        f"## Coordination Roles\n"
        f"\n"
        f"{coord_roles}\n"
    )

    return {
        "docs/agents/README.md": readme.strip() + "\n",
        "docs/agents/codex.md": codex.strip() + "\n",
        "docs/agents/harness-subagents.md": harness.strip() + "\n",
        "docs/agents/manifest.md": manifest_doc.strip() + "\n",
    }



def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Write content to path, or check if it matches. Returns True if OK."""
    if check:
        if not path.exists():
            try:
                label = str(path.relative_to(ROOT))
            except ValueError:
                label = str(path)
            print(f"  MISSING: {label}")
            return False
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            try:
                label = str(path.relative_to(ROOT))
            except ValueError:
                label = str(path)
            print(f"  STALE: {label}")
            return False
        return True
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return True


# ---------------------------------------------------------------------------
# Main generation
# ---------------------------------------------------------------------------

def generate_all(manifest: dict, check: bool = False, target: str | None = None) -> bool:
    validate_manifest(manifest)
    roles = manifest["roles"]
    profiles = manifest["tool_profiles"]
    ok = True

    targets = set(TARGETS) if target is None else {target}

    # Packaged Codex ControlStore runtime kit
    if "codex" in targets:
        packaged_root = ROOT / "src" / "multi_agent_brief" / "runtime_kits" / "codex"
        if not write_or_check(
            packaged_root / "config.toml",
            render_codex_config(manifest),
            check,
        ):
            ok = False
        for name in PACKAGED_CODEX_ROLE_IDS:
            path = packaged_root / "agents" / f"briefloop-{name}.toml"
            content = render_packaged_codex_agent(name, roles[name])
            if not write_or_check(path, content, check):
                ok = False

    # Docs
    if "docs" in targets:
        docs = render_docs(manifest)
        for rel_path, content in docs.items():
            path = ROOT / rel_path
            if not write_or_check(path, content, check):
                ok = False

    return ok


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_agent_configs",
        description="Generate platform-specific agent adapter files from agent_roles.yaml. AGENTS.md and .agents/skills are hand-maintained operating contracts.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Generate platform adapter files")
    group.add_argument("--check", action="store_true", help="Check if platform adapter files are up to date")
    parser.add_argument("--target", choices=sorted(TARGETS),
                        help="Generate only a specific target: codex or docs.")
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH,
                        help="Path to agent_roles.yaml")

    args = parser.parse_args(argv)

    manifest = load_manifest(args.manifest)
    ok = generate_all(
        manifest,
        check=args.check,
        target=args.target,
    )

    if args.check:
        if ok:
            print("All generated files are up to date.")
        else:
            print("Generated adapter files are stale. Run: python scripts/generate_agent_configs.py --write")
        return 0 if ok else 1
    else:
        print("Generated platform adapter configs.")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
